#!/usr/bin/env bash
# cross-contamination-audit.sh
# Per FEEP Article IV.5 — quarterly audit of entity isolation
# Run from repo root: ./scripts/cross-contamination-audit.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

DATE="$(date '+%Y-%m-%d')"
QUARTER="$(date '+%Y-Q')$((($(date '+%-m')-1)/3 + 1))"
OUT="docs/feep/audits/cross-contamination-${QUARTER}.md"
mkdir -p "$(dirname "$OUT")"

echo "Running cross-contamination audit → $OUT"

{
  echo "# Cross-Contamination Audit — $QUARTER"
  echo "**Date:** $DATE"
  echo "**Per:** FEEP Article IV.5 + Cross-Company Isolation Doctrine §5"
  echo "**Generator:** scripts/cross-contamination-audit.sh"
  echo ""
  echo "---"
  echo ""

  echo "## 1. CODE-LEVEL CHECKS"
  echo ""

  # Check 1: Shared API keys across entity folders
  echo "### 1.1 Shared API Keys / Secrets"
  echo ""
  echo "Pattern search for likely secrets across entity docs:"
  echo '```'
  # Look for stripe keys, AWS keys, etc. in any docs/{entity}/ folder
  for entity_dir in docs/horizon-aba docs/poolcurrent; do
    if [ -d "$entity_dir" ]; then
      echo "Scanning $entity_dir..."
      grep -rn "sk_live_\|sk_test_\|AKIA\|api_key.*=.*['\"]" "$entity_dir" 2>/dev/null | head -10 || echo "  (no matches — good)"
    fi
  done
  echo '```'
  echo ""

  # Check 2: Cross-entity references in code/docs
  echo "### 1.2 Cross-Entity References in Operational Docs"
  echo ""
  echo "Counts of unexpected cross-references:"
  echo ""
  if [ -d "docs/horizon-aba" ] && [ -d "docs/poolcurrent" ]; then
    horizon_in_pool=$(grep -rli "horizon" docs/poolcurrent/ 2>/dev/null | grep -v "README.md" | grep -v "FEEP" | grep -v "feep" | wc -l || echo 0)
    pool_in_horizon=$(grep -rli "poolcurrent" docs/horizon-aba/ 2>/dev/null | grep -v "feep" | wc -l || echo 0)
    echo "- PoolCurrent docs mentioning Horizon (excluding doctrine refs): $horizon_in_pool"
    echo "- Horizon docs mentioning PoolCurrent (excluding doctrine refs): $pool_in_horizon"
  fi
  echo ""

  echo "## 2. DOCUMENTATION CHECKS"
  echo ""

  # Check 3: Each entity has its own folders
  echo "### 2.1 Entity Folder Structure"
  echo ""
  echo "| Entity | docs/ | governance/ | legal/ | security/ | operations/ |"
  echo "|---|---|---|---|---|---|"
  for entity in horizon-aba poolcurrent; do
    folder="docs/${entity}"
    [ -d "$folder" ] && d="✅" || d="❌"
    [ -d "${folder}/governance" ] && g="✅" || g="—"
    [ -d "${folder}/legal" ] && l="✅" || l="—"
    [ -d "${folder}/security" ] && s="✅" || s="—"
    [ -d "${folder}/operations" ] && o="✅" || o="—"
    echo "| $entity | $d | $g | $l | $s | $o |"
  done
  echo ""

  # Check 4: Exceptions documented
  echo "### 2.2 Documented Exceptions"
  echo ""
  if [ -d "docs/feep/exceptions" ]; then
    exception_count=$(find docs/feep/exceptions -name "*.md" 2>/dev/null | wc -l)
    echo "Active exceptions: $exception_count"
    if [ "$exception_count" -gt 0 ]; then
      echo ""
      echo '```'
      ls docs/feep/exceptions/*.md 2>/dev/null || true
      echo '```'
    fi
  else
    echo "No exceptions folder yet (good — no exceptions filed)."
  fi
  echo ""

  echo "## 3. PRODUCTION CHECKS (Manual — Not Automated From This Sandbox)"
  echo ""
  echo "The following must be verified by Engineering Lead against actual production:"
  echo ""
  echo "- [ ] No customer email appears in multiple entity databases"
  echo "- [ ] No shared Stripe customer ID across entities"
  echo "- [ ] No shared database connection strings"
  echo "- [ ] No subdomain crossover (e.g., admin.entity1.com doesn't resolve to entity2 infra)"
  echo "- [ ] DNS records correctly attributed"
  echo "- [ ] Shared cloud account isolation verified (separate IAM users per entity)"
  echo ""
  echo "**Engineering Lead must check production and update this audit with findings.**"
  echo ""

  echo "## 4. FINDINGS SUMMARY"
  echo ""
  echo "| Severity | Count | Action |"
  echo "|---|---|---|"
  echo "| Critical | 0 | — |"
  echo "| High | 0 | — |"
  echo "| Medium | 0 | — |"
  echo "| Low | 0 | — |"
  echo ""
  echo "*(Counselor + Engineering Lead update this table after manual verification.)*"
  echo ""

  echo "## 5. SIGN-OFF"
  echo ""
  echo '```'
  echo "Counselor:           ___________________ Date: __________"
  echo "Engineering Lead:    ___________________ Date: __________"
  echo "Chief of Staff:      ___________________ Date: __________"
  echo '```'
  echo ""
  echo "---"
  echo "*Generated by scripts/cross-contamination-audit.sh on $DATE*"
} > "$OUT"

echo "Done. Audit report at: $OUT"
echo ""
echo "Next: Engineering Lead + Counselor complete the manual checks in Section 3 + 4."
